use_directory_urls: false
site_author: Justin Perdok
copyright: SomeTestModule is licensed under <a href='https://github.com/justin-p/SomeTestModule/blob/master/License.md'>this</a> license
theme: readthedocs
site_name: SomeTestModule Docs
pages:
- Acknowledgements: Acknowledgements.md
- ChangeLog: ChangeLog.md
- Contributing: Contributing.md
- index: index.md
- Functions: Functions/Write-SomeTestModule.md
repo_url: https://github.com/justin-p/SomeTestModule

